# Generated by Django 4.2.6 on 2023-10-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback_changed_by_admin_feedback_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
